// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbZNyevCbNfKwf2Qw5zWKKOEx5ElsGY_o',
    appId: '1:304643047343:web:8df8cdc59bea7faf1e795a',
    messagingSenderId: '304643047343',
    projectId: 'bwa-flutix-f1896',
    authDomain: 'bwa-flutix-f1896.firebaseapp.com',
    databaseURL: 'https://bwa-flutix-f1896-default-rtdb.firebaseio.com',
    storageBucket: 'bwa-flutix-f1896.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByHA2ArJ4SJzi8YFtw1P1WYZrYmMGoGfo',
    appId: '1:304643047343:android:ae9461d338d5aa7d1e795a',
    messagingSenderId: '304643047343',
    projectId: 'bwa-flutix-f1896',
    databaseURL: 'https://bwa-flutix-f1896-default-rtdb.firebaseio.com',
    storageBucket: 'bwa-flutix-f1896.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD36h0YbfzfrGCyBbtOq9cU93ahxbhCTc',
    appId: '1:304643047343:ios:30562446e4063fbd1e795a',
    messagingSenderId: '304643047343',
    projectId: 'bwa-flutix-f1896',
    databaseURL: 'https://bwa-flutix-f1896-default-rtdb.firebaseio.com',
    storageBucket: 'bwa-flutix-f1896.appspot.com',
    iosClientId: '304643047343-vubcn9fcs1naavqlmct8vo2e6b4i1u3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.bwaFlutix',
  );
}
